const STYLE_ID = 'dsh-desktop-shortcut-menu-styles'
const CSS = `
.dshSidebarShortcuts{display:flex;flex:none;flex-direction:column;gap:4px;width:100%;margin-bottom:8px}.dshSidebarShortcut{display:flex;width:100%;min-height:36px;align-items:center;gap:8px;padding:7px 8px;box-sizing:border-box;border:0;border-radius:8px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer;font:inherit;line-height:22px;text-align:left}.dshSidebarShortcut:hover{background:var(--dsw-alias-interactive-bg-hover)}.dshSidebarShortcut:focus-visible{outline:2px solid var(--dsw-alias-label-primary);outline-offset:-2px}.dshShortcutGlyph{display:inline-flex;flex:none;align-items:center;justify-content:center;width:16px;height:16px}.dshShortcutGlyph svg{width:16px;height:16px}.dshSidebarShortcuts[data-wide=false]{gap:12px;margin-bottom:12px}.dshSidebarShortcuts[data-wide=false] .dshSidebarShortcut{width:36px;height:36px;justify-content:center;padding:0;color:var(--dsw-alias-label-primary)}.dshShortcutSettings{display:flex;flex-direction:column;gap:8px;padding:16px 0;border-bottom:.5px solid var(--dsw-alias-border-l2)}.dshShortcutSettings header{display:flex;flex-direction:column;gap:4px}.dshShortcutSettings header h3{margin:0;font-size:14px;font-weight:400;line-height:22px;color:var(--dsw-alias-label-primary)}.dshShortcutSettings header p{margin:0;font-size:12px;font-weight:400;line-height:18px;color:var(--dsw-alias-label-tertiary)}.dshShortcutGroups{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px;margin-top:4px}.dshShortcutGroup{display:flex;flex-direction:column;gap:4px;min-width:0;padding:12px;border:.5px solid var(--dsw-alias-border-l2);border-radius:12px}.dshShortcutGroup h4{margin:0 0 2px;color:var(--dsw-alias-label-tertiary);font-size:12px;font-weight:400;line-height:18px}.dshShortcutRow{display:flex;min-height:36px;align-items:center;gap:8px;padding:0 4px;border-radius:6px;font-size:14px;line-height:22px;color:var(--dsw-alias-label-primary)}.dshShortcutRow:hover{background:var(--dsw-alias-interactive-bg-hover)}.dshShortcutRow .dshShortcutGlyph{color:var(--dsw-alias-label-secondary)}.dshShortcutRow .dshShortcutGlyph svg{width:16px;height:16px}.dshShortcutRow>span:nth-child(2){min-width:0;flex:1}.dshShortcutRow button{min-width:30px;height:28px;padding:0 8px;border:.5px solid var(--dsw-alias-border-l2);border-radius:6px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer;font:inherit;font-size:12px;line-height:18px}.dshShortcutRow button:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}.dshShortcutRow button:disabled{cursor:default;opacity:.38}.dshShortcutActions{display:flex;gap:4px}.dshShortcutSettings button:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:2px}@media(max-width:620px){.dshShortcutGroups{grid-template-columns:1fr}}
`
export function installShortcutMenuStyles(document: Document = globalThis.document): () => void {
  if (document.getElementById(STYLE_ID) !== null) return () => {}
  const style = document.createElement('style'); style.id = STYLE_ID; style.textContent = CSS; document.head.append(style)
  return () => { style.remove() }
}
