 
// Generated by scripts/sync-openclaw-chat-commands.mjs
// Source: installed openclaw package in node_modules

export type GeneratedOpenClawArgChoice = string | { value: string; label: string };

export type GeneratedOpenClawArgDefinition = {
  name: string;
  description: string;
  required?: boolean;
  captureRemaining?: boolean;
  choices?: GeneratedOpenClawArgChoice[];
};

export type GeneratedOpenClawCommandDefinition = {
  key: string;
  description: string;
  textAliases: string[];
  acceptsArgs?: boolean;
  category?: string;
  args?: GeneratedOpenClawArgDefinition[];
};

export const GENERATED_OPENCLAW_CHAT_COMMANDS: GeneratedOpenClawCommandDefinition[] = [
  {
    "key": "help",
    "description": "Show available commands.",
    "textAliases": [
      "/help"
    ],
    "acceptsArgs": false,
    "category": "status"
  },
  {
    "key": "commands",
    "description": "List all slash commands.",
    "textAliases": [
      "/commands"
    ],
    "acceptsArgs": false,
    "category": "status"
  },
  {
    "key": "tools",
    "description": "List available runtime tools.",
    "textAliases": [
      "/tools"
    ],
    "acceptsArgs": true,
    "category": "status",
    "args": [
      {
        "name": "mode",
        "description": "compact or verbose",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "compact",
          "verbose"
        ]
      }
    ]
  },
  {
    "key": "skill",
    "description": "Run a skill by name.",
    "textAliases": [
      "/skill"
    ],
    "acceptsArgs": true,
    "category": "tools",
    "args": [
      {
        "name": "name",
        "description": "Skill name",
        "required": true,
        "captureRemaining": false
      },
      {
        "name": "input",
        "description": "Skill input",
        "required": false,
        "captureRemaining": true
      }
    ]
  },
  {
    "key": "status",
    "description": "Show current status.",
    "textAliases": [
      "/status"
    ],
    "acceptsArgs": false,
    "category": "status"
  },
  {
    "key": "tasks",
    "description": "List background tasks for this session.",
    "textAliases": [
      "/tasks"
    ],
    "acceptsArgs": false,
    "category": "status"
  },
  {
    "key": "allowlist",
    "description": "List/add/remove allowlist entries.",
    "textAliases": [
      "/allowlist"
    ],
    "acceptsArgs": true,
    "category": "management"
  },
  {
    "key": "approve",
    "description": "Approve or deny exec requests.",
    "textAliases": [
      "/approve"
    ],
    "acceptsArgs": true,
    "category": "management"
  },
  {
    "key": "context",
    "description": "Explain how context is built and used.",
    "textAliases": [
      "/context"
    ],
    "acceptsArgs": true,
    "category": "status"
  },
  {
    "key": "btw",
    "description": "Ask a side question without changing future session context.",
    "textAliases": [
      "/btw"
    ],
    "acceptsArgs": true,
    "category": "tools"
  },
  {
    "key": "export-session",
    "description": "Export current session to HTML file with full system prompt.",
    "textAliases": [
      "/export-session",
      "/export"
    ],
    "acceptsArgs": true,
    "category": "status",
    "args": [
      {
        "name": "path",
        "description": "Output path (default: workspace)",
        "required": false,
        "captureRemaining": false
      }
    ]
  },
  {
    "key": "tts",
    "description": "Control text-to-speech (TTS).",
    "textAliases": [
      "/tts"
    ],
    "acceptsArgs": true,
    "category": "media",
    "args": [
      {
        "name": "action",
        "description": "TTS action",
        "required": false,
        "captureRemaining": false,
        "choices": [
          {
            "value": "on",
            "label": "On"
          },
          {
            "value": "off",
            "label": "Off"
          },
          {
            "value": "status",
            "label": "Status"
          },
          {
            "value": "provider",
            "label": "Provider"
          },
          {
            "value": "limit",
            "label": "Limit"
          },
          {
            "value": "summary",
            "label": "Summary"
          },
          {
            "value": "audio",
            "label": "Audio"
          },
          {
            "value": "help",
            "label": "Help"
          }
        ]
      },
      {
        "name": "value",
        "description": "Provider, limit, or text",
        "required": false,
        "captureRemaining": true
      }
    ]
  },
  {
    "key": "whoami",
    "description": "Show your sender id.",
    "textAliases": [
      "/whoami",
      "/id"
    ],
    "acceptsArgs": false,
    "category": "status"
  },
  {
    "key": "session",
    "description": "Manage session-level settings (for example /session idle).",
    "textAliases": [
      "/session"
    ],
    "acceptsArgs": true,
    "category": "session",
    "args": [
      {
        "name": "action",
        "description": "idle | max-age",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "idle",
          "max-age"
        ]
      },
      {
        "name": "value",
        "description": "Duration (24h, 90m) or off",
        "required": false,
        "captureRemaining": true
      }
    ]
  },
  {
    "key": "subagents",
    "description": "List, kill, log, spawn, or steer subagent runs for this session.",
    "textAliases": [
      "/subagents"
    ],
    "acceptsArgs": true,
    "category": "management",
    "args": [
      {
        "name": "action",
        "description": "list | kill | log | info | send | steer | spawn",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "list",
          "kill",
          "log",
          "info",
          "send",
          "steer",
          "spawn"
        ]
      },
      {
        "name": "target",
        "description": "Run id, index, or session key",
        "required": false,
        "captureRemaining": false
      },
      {
        "name": "value",
        "description": "Additional input (limit/message)",
        "required": false,
        "captureRemaining": true
      }
    ]
  },
  {
    "key": "acp",
    "description": "Manage ACP sessions and runtime options.",
    "textAliases": [
      "/acp"
    ],
    "acceptsArgs": true,
    "category": "management",
    "args": [
      {
        "name": "action",
        "description": "Action to run",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "spawn",
          "cancel",
          "steer",
          "close",
          "sessions",
          "status",
          "set-mode",
          "set",
          "cwd",
          "permissions",
          "timeout",
          "model",
          "reset-options",
          "doctor",
          "install",
          "help"
        ]
      },
      {
        "name": "value",
        "description": "Action arguments",
        "required": false,
        "captureRemaining": true
      }
    ]
  },
  {
    "key": "focus",
    "description": "Bind this thread (Discord) or topic/conversation (Telegram) to a session target.",
    "textAliases": [
      "/focus"
    ],
    "acceptsArgs": true,
    "category": "management",
    "args": [
      {
        "name": "target",
        "description": "Subagent label/index or session key/id/label",
        "required": false,
        "captureRemaining": true
      }
    ]
  },
  {
    "key": "unfocus",
    "description": "Remove the current thread (Discord) or topic/conversation (Telegram) binding.",
    "textAliases": [
      "/unfocus"
    ],
    "acceptsArgs": false,
    "category": "management"
  },
  {
    "key": "agents",
    "description": "List thread-bound agents for this session.",
    "textAliases": [
      "/agents"
    ],
    "acceptsArgs": false,
    "category": "management"
  },
  {
    "key": "kill",
    "description": "Kill a running subagent (or all).",
    "textAliases": [
      "/kill"
    ],
    "acceptsArgs": true,
    "category": "management",
    "args": [
      {
        "name": "target",
        "description": "Label, run id, index, or all",
        "required": false,
        "captureRemaining": false
      }
    ]
  },
  {
    "key": "steer",
    "description": "Send guidance to a running subagent.",
    "textAliases": [
      "/steer",
      "/tell"
    ],
    "acceptsArgs": true,
    "category": "management",
    "args": [
      {
        "name": "target",
        "description": "Label, run id, or index",
        "required": false,
        "captureRemaining": false
      },
      {
        "name": "message",
        "description": "Steering message",
        "required": false,
        "captureRemaining": true
      }
    ]
  },
  {
    "key": "config",
    "description": "Show or set config values.",
    "textAliases": [
      "/config"
    ],
    "acceptsArgs": true,
    "category": "management",
    "args": [
      {
        "name": "action",
        "description": "show | get | set | unset",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "show",
          "get",
          "set",
          "unset"
        ]
      },
      {
        "name": "path",
        "description": "Config path",
        "required": false,
        "captureRemaining": false
      },
      {
        "name": "value",
        "description": "Value for set",
        "required": false,
        "captureRemaining": true
      }
    ]
  },
  {
    "key": "mcp",
    "description": "Show or set OpenClaw MCP servers.",
    "textAliases": [
      "/mcp"
    ],
    "acceptsArgs": true,
    "category": "management",
    "args": [
      {
        "name": "action",
        "description": "show | get | set | unset",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "show",
          "get",
          "set",
          "unset"
        ]
      },
      {
        "name": "path",
        "description": "MCP server name",
        "required": false,
        "captureRemaining": false
      },
      {
        "name": "value",
        "description": "JSON config for set",
        "required": false,
        "captureRemaining": true
      }
    ]
  },
  {
    "key": "plugins",
    "description": "List, show, enable, or disable plugins.",
    "textAliases": [
      "/plugins",
      "/plugin"
    ],
    "acceptsArgs": true,
    "category": "management",
    "args": [
      {
        "name": "action",
        "description": "list | show | get | enable | disable",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "list",
          "show",
          "get",
          "enable",
          "disable"
        ]
      },
      {
        "name": "path",
        "description": "Plugin id or name",
        "required": false,
        "captureRemaining": false
      }
    ]
  },
  {
    "key": "debug",
    "description": "Set runtime debug overrides.",
    "textAliases": [
      "/debug"
    ],
    "acceptsArgs": true,
    "category": "management",
    "args": [
      {
        "name": "action",
        "description": "show | reset | set | unset",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "show",
          "reset",
          "set",
          "unset"
        ]
      },
      {
        "name": "path",
        "description": "Debug path",
        "required": false,
        "captureRemaining": false
      },
      {
        "name": "value",
        "description": "Value for set",
        "required": false,
        "captureRemaining": true
      }
    ]
  },
  {
    "key": "usage",
    "description": "Usage footer or cost summary.",
    "textAliases": [
      "/usage"
    ],
    "acceptsArgs": true,
    "category": "options",
    "args": [
      {
        "name": "mode",
        "description": "off, tokens, full, or cost",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "off",
          "tokens",
          "full",
          "cost"
        ]
      }
    ]
  },
  {
    "key": "stop",
    "description": "Stop the current run.",
    "textAliases": [
      "/stop"
    ],
    "acceptsArgs": false,
    "category": "session"
  },
  {
    "key": "restart",
    "description": "Restart OpenClaw.",
    "textAliases": [
      "/restart"
    ],
    "acceptsArgs": false,
    "category": "tools"
  },
  {
    "key": "activation",
    "description": "Set group activation mode.",
    "textAliases": [
      "/activation"
    ],
    "acceptsArgs": true,
    "category": "management",
    "args": [
      {
        "name": "mode",
        "description": "mention or always",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "mention",
          "always"
        ]
      }
    ]
  },
  {
    "key": "send",
    "description": "Set send policy.",
    "textAliases": [
      "/send"
    ],
    "acceptsArgs": true,
    "category": "management",
    "args": [
      {
        "name": "mode",
        "description": "on, off, or inherit",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "on",
          "off",
          "inherit"
        ]
      }
    ]
  },
  {
    "key": "reset",
    "description": "Reset the current session.",
    "textAliases": [
      "/reset"
    ],
    "acceptsArgs": true,
    "category": "session"
  },
  {
    "key": "new",
    "description": "Start a new session.",
    "textAliases": [
      "/new"
    ],
    "acceptsArgs": true,
    "category": "session"
  },
  {
    "key": "compact",
    "description": "Compact the session context.",
    "textAliases": [
      "/compact"
    ],
    "acceptsArgs": true,
    "category": "session",
    "args": [
      {
        "name": "instructions",
        "description": "Extra compaction instructions",
        "required": false,
        "captureRemaining": true
      }
    ]
  },
  {
    "key": "think",
    "description": "Set thinking level.",
    "textAliases": [
      "/think",
      "/thinking",
      "/t"
    ],
    "acceptsArgs": true,
    "category": "options",
    "args": [
      {
        "name": "level",
        "description": "off, minimal, low, medium, high, xhigh",
        "required": false,
        "captureRemaining": false
      }
    ]
  },
  {
    "key": "verbose",
    "description": "Toggle verbose mode.",
    "textAliases": [
      "/verbose",
      "/v"
    ],
    "acceptsArgs": true,
    "category": "options",
    "args": [
      {
        "name": "mode",
        "description": "on or off",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "on",
          "off"
        ]
      }
    ]
  },
  {
    "key": "fast",
    "description": "Toggle fast mode.",
    "textAliases": [
      "/fast"
    ],
    "acceptsArgs": true,
    "category": "options",
    "args": [
      {
        "name": "mode",
        "description": "status, on, or off",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "status",
          "on",
          "off"
        ]
      }
    ]
  },
  {
    "key": "reasoning",
    "description": "Toggle reasoning visibility.",
    "textAliases": [
      "/reasoning",
      "/reason"
    ],
    "acceptsArgs": true,
    "category": "options",
    "args": [
      {
        "name": "mode",
        "description": "on, off, or stream",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "on",
          "off",
          "stream"
        ]
      }
    ]
  },
  {
    "key": "elevated",
    "description": "Toggle elevated mode.",
    "textAliases": [
      "/elevated",
      "/elev"
    ],
    "acceptsArgs": true,
    "category": "options",
    "args": [
      {
        "name": "mode",
        "description": "on, off, ask, or full",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "on",
          "off",
          "ask",
          "full"
        ]
      }
    ]
  },
  {
    "key": "exec",
    "description": "Set exec defaults for this session.",
    "textAliases": [
      "/exec"
    ],
    "acceptsArgs": true,
    "category": "options",
    "args": [
      {
        "name": "host",
        "description": "sandbox, gateway, or node",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "sandbox",
          "gateway",
          "node"
        ]
      },
      {
        "name": "security",
        "description": "deny, allowlist, or full",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "deny",
          "allowlist",
          "full"
        ]
      },
      {
        "name": "ask",
        "description": "off, on-miss, or always",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "off",
          "on-miss",
          "always"
        ]
      },
      {
        "name": "node",
        "description": "Node id or name",
        "required": false,
        "captureRemaining": false
      }
    ]
  },
  {
    "key": "model",
    "description": "Show or set the model.",
    "textAliases": [
      "/model"
    ],
    "acceptsArgs": true,
    "category": "options",
    "args": [
      {
        "name": "model",
        "description": "Model id (provider/model or id)",
        "required": false,
        "captureRemaining": false
      }
    ]
  },
  {
    "key": "models",
    "description": "List model providers or provider models.",
    "textAliases": [
      "/models"
    ],
    "acceptsArgs": true,
    "category": "options"
  },
  {
    "key": "queue",
    "description": "Adjust queue settings.",
    "textAliases": [
      "/queue"
    ],
    "acceptsArgs": true,
    "category": "options",
    "args": [
      {
        "name": "mode",
        "description": "queue mode",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "steer",
          "interrupt",
          "followup",
          "collect",
          "steer-backlog"
        ]
      },
      {
        "name": "debounce",
        "description": "debounce duration (e.g. 500ms, 2s)",
        "required": false,
        "captureRemaining": false
      },
      {
        "name": "cap",
        "description": "queue cap",
        "required": false,
        "captureRemaining": false
      },
      {
        "name": "drop",
        "description": "drop policy",
        "required": false,
        "captureRemaining": false,
        "choices": [
          "old",
          "new",
          "summarize"
        ]
      }
    ]
  },
  {
    "key": "bash",
    "description": "Run host shell commands (host-only).",
    "textAliases": [
      "/bash"
    ],
    "acceptsArgs": true,
    "category": "tools",
    "args": [
      {
        "name": "command",
        "description": "Shell command",
        "required": false,
        "captureRemaining": true
      }
    ]
  }
] as const;
