const STYLE_ID = 'dsh-desktop-management-styles'

const CSS = `
.dshIntegrations{display:flex;flex-direction:column;gap:20px;width:100%;max-width:880px;min-width:0;box-sizing:border-box;container-type:inline-size;padding:2px 0 36px;color:var(--dsw-alias-label-primary)}
.dshIntegrationsHeader,.dshIntegrationsEditorHeader,.dshIntegrationsMcpHeader,.dshIntegrationsToolbar,.dshIntegrationsEditorFooter,.dshIntegrationsDetailHeader{display:flex;align-items:center;justify-content:space-between;gap:14px;min-width:0}.dshIntegrationsHeader{align-items:flex-start}.dshIntegrationsHeader h2,.dshIntegrationsEditor h3,.dshIntegrationsSkillInlineDetail h4{margin:0;font-weight:600}.dshIntegrationsHeader h2{font-size:22px;line-height:1.35}.dshIntegrationsHeader p,.dshIntegrationsDetailHeader p,.dshIntegrationsToolbar p{max-width:680px;margin:6px 0 0;color:var(--dsw-alias-label-secondary);font-size:13px;line-height:1.6}
.dshIntegrationsBody,.dshIntegrationsList,.dshIntegrationsSkillGroup{display:flex;flex-direction:column;gap:8px;min-width:0}.dshIntegrationsBody{gap:16px}.dshIntegrationsSkillGroup h3{margin:8px 2px 0;color:var(--dsw-alias-label-secondary);font-size:12px;font-weight:500}
.dshIntegrationsSearch{position:relative;display:flex;align-items:center}.dshIntegrationsSearch svg{position:absolute;left:11px;width:15px;height:15px;color:var(--dsw-alias-label-secondary)}
.dshIntegrationsSearch input,.dshIntegrationsEditor input:not([type=checkbox]),.dshIntegrationsEditor textarea,.dshIntegrationsImport textarea{box-sizing:border-box;width:100%;min-height:36px;padding:7px 11px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;outline:none;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);font:inherit;font-size:13px}.dshIntegrationsSearch input{padding-left:34px}.dshIntegrationsEditor textarea,.dshIntegrationsImport textarea{line-height:1.5;resize:vertical}.dshIntegrationsSearch input:focus,.dshIntegrationsEditor input:not([type=checkbox]):focus,.dshIntegrationsEditor textarea:focus,.dshIntegrationsImport textarea:focus{border-color:var(--dsw-alias-brand-primary);box-shadow:0 0 0 2px color-mix(in srgb,var(--dsw-alias-brand-primary) 18%,transparent)}
.dshIntegrationsRow,.dshIntegrationsMcp{box-sizing:border-box;border:1px solid var(--dsw-alias-border-l1);border-radius:10px;background:var(--dsw-alias-bg-layer-1);transition:border-color .15s ease,background .15s ease}.dshIntegrationsRow{display:flex;align-items:center;justify-content:space-between;gap:16px;min-width:0;padding:12px 14px}.dshIntegrationsMcp{padding:14px}.dshIntegrationsRow:hover,.dshIntegrationsMcp:hover{border-color:var(--dsw-alias-border-l2);background:var(--dsw-alias-interactive-bg-hover)}
.dshIntegrationsRowMain{display:flex;flex:1;flex-direction:column;align-items:flex-start;gap:4px;min-width:0}.dshIntegrationsRowTitle,.dshIntegrationsSkillName{font-size:14px;font-weight:600;overflow-wrap:anywhere}.dshIntegrationsRowDescription{color:var(--dsw-alias-label-secondary);font-size:12px;line-height:1.5;overflow-wrap:anywhere}.dshIntegrationsMeta{display:flex;flex-wrap:wrap;gap:6px;margin:2px 0 0;color:var(--dsw-alias-label-secondary);font-size:11px}.dshIntegrationsMeta>span{display:inline-flex;align-items:center;min-height:20px;max-width:220px;padding:1px 8px;overflow:hidden;border-radius:999px;background:var(--dsw-alias-bg-layer-2);text-overflow:ellipsis;white-space:nowrap}.dshIntegrationsMeta [data-state=running]{color:var(--dsw-alias-state-success-primary)}.dshIntegrationsMeta [data-state=error],.dshIntegrationsServerError{color:var(--dsw-alias-state-error-primary)}
.dshIntegrationsRowActions{display:flex;align-items:center;gap:8px;flex:0 0 auto}.dshIntegrationsStatus{color:var(--dsw-alias-label-secondary);font-size:11px;white-space:nowrap}.dshIntegrationsIconButton,.dshIntegrationsCommand,.dshIntegrationsDanger{display:inline-flex;align-items:center;justify-content:center;gap:7px;border:1px solid var(--dsw-alias-border-l2);background:transparent;color:var(--dsw-alias-label-primary);cursor:pointer;font:inherit;font-size:12px}.dshIntegrationsIconButton{width:30px;height:30px;padding:0;border-radius:999px;color:var(--dsw-alias-label-secondary)}.dshIntegrationsIconButton svg,.dshIntegrationsCommand svg,.dshIntegrationsDanger svg{width:14px;height:14px}.dshIntegrationsCommand,.dshIntegrationsDanger{min-height:32px;padding:5px 13px;border-radius:999px}.dshIntegrationsIconButton:hover:not(:disabled),.dshIntegrationsCommand:hover:not(:disabled),.dshIntegrationsDanger:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover)}.dshIntegrationsIconButton[data-danger=true],.dshIntegrationsDanger{color:var(--dsw-alias-state-error-primary)}.dshIntegrationsIconButton:disabled,.dshIntegrationsCommand:disabled,.dshIntegrationsDanger:disabled{cursor:default;opacity:.45}
.dshIntegrationsToggle{position:relative;flex:0 0 auto;width:34px;height:20px;padding:0;border:0;border-radius:10px;background:var(--dsw-alias-border-l2);cursor:pointer}.dshIntegrationsToggle[aria-checked=true]{background:var(--dsw-alias-brand-primary)}.dshIntegrationsToggle span{position:absolute;top:3px;left:3px;width:14px;height:14px;border-radius:50%;background:#fff;transition:transform .15s}.dshIntegrationsToggle[aria-checked=true] span{transform:translateX(14px)}.dshIntegrationsToggle:disabled{cursor:default;opacity:.45}
.dshIntegrationsEditor,.dshIntegrationsImport,.dshIntegrationsRecycle,.dshIntegrationsToolbar{display:flex;flex-direction:column;gap:14px;padding:15px;border:1px solid var(--dsw-alias-border-l1);border-radius:10px;background:var(--dsw-alias-bg-layer-1)}.dshIntegrationsToolbar{align-items:center;flex-direction:row}.dshIntegrationsToolbar p{flex:1;margin:0}.dshIntegrationsEditor label,.dshIntegrationsImport label{display:flex;flex-direction:column;gap:7px;color:var(--dsw-alias-label-secondary);font-size:12px}.dshIntegrationsEditor fieldset{margin:0;padding:0;border:0}.dshIntegrationsEditor legend{margin-bottom:6px;color:var(--dsw-alias-label-secondary);font-size:12px}.dshIntegrationsSegments{display:flex;gap:3px;width:max-content;padding:3px;border:1px solid var(--dsw-alias-border-l1);border-radius:8px}.dshIntegrationsSegments button{min-height:30px;padding:4px 12px;border:0;border-radius:6px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer;font:inherit;font-size:12px}.dshIntegrationsSegments button[aria-pressed=true]{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary);font-weight:600}.dshIntegrationsEditorFooter .dshIntegrationsEnabled{display:flex;align-items:center;gap:7px}.dshIntegrationsEnabled input[type=checkbox]{width:16px;height:16px;margin:0;accent-color:var(--dsw-alias-brand-primary)}
.dshIntegrationsMcp{display:block}.dshIntegrationsMcpHeader>div:first-child{display:flex;flex:1;flex-direction:column;gap:4px;min-width:0}.dshIntegrationsServerError{margin:8px 0 0;font-size:12px;overflow-wrap:anywhere}.dshIntegrationsTools{display:flex;flex-wrap:wrap;gap:5px;margin-top:9px}.dshIntegrationsTools span{max-width:100%;padding:3px 7px;border-radius:5px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-secondary);font-size:11px;overflow-wrap:anywhere}
.dshIntegrationsSkillRow{align-items:flex-start;flex-wrap:wrap;cursor:pointer}.dshIntegrationsSkillRow .dshIntegrationsRowDescription{display:-webkit-box;max-width:620px;overflow:hidden;-webkit-box-orient:vertical;-webkit-line-clamp:2}.dshIntegrationsSkillRow .dshIntegrationsRowDescription[data-expanded]{display:block;max-width:none;overflow:visible}.dshIntegrationsTextButton{padding:0;border:0;background:transparent;color:var(--dsw-alias-brand-primary);cursor:pointer;font:inherit;font-size:12px;line-height:1.4}.dshIntegrationsTextButton:hover{text-decoration:underline;text-underline-offset:2px}.dshIntegrationsSkillAside{display:flex;align-items:center;justify-content:flex-end;gap:14px;flex:0 0 auto;min-width:0}.dshIntegrationsSkillAside .dshIntegrationsMeta{margin:0;flex-wrap:nowrap}.dshIntegrationsSkillActions{display:flex;align-items:center;gap:12px}.dshIntegrationsSkillControl{display:flex;align-items:center;gap:6px;min-width:0;color:var(--dsw-alias-label-secondary);font-size:11px;white-space:nowrap}
.dshIntegrationsSkillInlineDetail{display:flex;flex:0 0 100%;box-sizing:border-box;flex-direction:column;gap:14px;margin:12px -14px -12px;padding:14px;border:0;border-top:1px solid var(--dsw-alias-border-l1);border-radius:0;background:var(--dsw-alias-bg-layer-2)}.dshIntegrationsSkillInlineDetail h4{font-size:14px}.dshIntegrationsSkillInlineDetail .dshIntegrationsDetailHeader p{margin:4px 0 0;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:1.5}.dshIntegrationsSkillInlineDetail dl{display:grid;gap:6px;margin:0}.dshIntegrationsSkillInlineDetail dl>div{display:grid;grid-template-columns:92px minmax(0,1fr);gap:10px}.dshIntegrationsSkillInlineDetail dt{color:var(--dsw-alias-label-secondary);font-size:12px}.dshIntegrationsSkillInlineDetail dd{min-width:0;margin:0;font-size:12px;overflow-wrap:anywhere}.dshIntegrationsSkillInlineDetail pre{max-height:360px;margin:0;padding:12px;overflow:auto;border:1px solid var(--dsw-alias-border-l1);border-radius:7px;background:var(--dsw-alias-bg-layer-1);font-size:12px;line-height:1.5;white-space:pre-wrap;overflow-wrap:anywhere}.dshIntegrationsDetailManagement{display:flex;flex-direction:column;gap:8px;padding:12px;border:1px solid var(--dsw-alias-border-l1);border-radius:8px;background:var(--dsw-alias-bg-layer-1)}.dshIntegrationsDetailManagement h4,.dshIntegrationsRecycle h3{margin:0;font-size:14px}
.dshIntegrationsError{padding:9px 11px;border-left:3px solid var(--dsw-alias-state-error-primary);border-radius:8px;background:color-mix(in srgb,var(--dsw-alias-state-error-primary) 8%,transparent);color:var(--dsw-alias-state-error-primary);font-size:12px;line-height:1.5}.dshIntegrationsEmpty{margin:0;padding:32px 16px;border:1px dashed var(--dsw-alias-border-l2);border-radius:10px;color:var(--dsw-alias-label-secondary);font-size:13px;text-align:center}.dshIntegrations button:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:2px}
@container(max-width:720px){.dshIntegrationsSkillAside{width:100%;justify-content:space-between;padding-top:8px;border-top:1px solid var(--dsw-alias-border-l1)}.dshIntegrationsSkillActions{flex-wrap:wrap}.dshIntegrationsSkillInlineDetail dl>div{grid-template-columns:1fr}}
@container(max-width:520px){.dshIntegrationsHeader,.dshIntegrationsToolbar,.dshIntegrationsMcpHeader{align-items:flex-start;flex-direction:column}.dshIntegrationsHeader .dshIntegrationsRowActions,.dshIntegrationsToolbar .dshIntegrationsRowActions,.dshIntegrationsMcpHeader .dshIntegrationsRowActions{width:100%;justify-content:flex-start}.dshIntegrationsRow{align-items:flex-start;flex-direction:column}.dshIntegrationsRowActions{flex-wrap:wrap}.dshIntegrationsSkillAside{align-items:flex-start;flex-direction:column;gap:8px}.dshIntegrationsSkillActions{gap:10px}.dshIntegrationsCommand{align-self:flex-start}}
`

export function installIntegrationsStyles(document: Document = globalThis.document): () => void {
  const existing = document.getElementById(STYLE_ID)
  if (existing !== null) return () => {}
  const style = document.createElement('style')
  style.id = STYLE_ID
  style.textContent = CSS
  document.head.append(style)
  return () => { style.remove() }
}
