import { mkdir, readFile, realpath, writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import { join } from 'node:path';
import type { IncomingMessage, ServerResponse } from 'http';
import type { HostApiContext } from '../context';
import { getSetting, setSetting } from '../../utils/store';
import { logger } from '../../utils/logger';
import { getOpenClawConfigDir } from '../../utils/paths';
import { parseJsonBody, sendJson } from '../route-utils';
import {
  type SecurityPolicy,
  type SecurityPolicySnapshot,
  DEFAULT_SECURITY_POLICY,
  SECURITY_RULE_DEFINITIONS,
  compactSecurityPaths,
  createSecurityPolicySnapshot,
  getManagedToolDenyForRules,
  mergeManagedToolDeny,
  normalizeToolPolicyEntries,
  normalizeSecurityPath,
  normalizeSecurityPolicy,
  normalizeSecurityRules,
} from '../../shared/security-policy';
import { normalizeReminders, type ReminderItem } from '../../shared/reminders';
import {
  readOpenClawConfigRecordRaw,
  updateOpenClawConfigRecord,
} from '../../utils/openclaw-config';

const SECURITY_POLICY_FILE = 'SECURITY_POLICY.md';
const AGENTS_FILE = 'AGENTS.md';
const POLICY_BEGIN = '<!-- clawclaw-security:begin -->';
const POLICY_END = '<!-- clawclaw-security:end -->';
const DEFAULT_WORKSPACE_POLICY_ROOT = join(getOpenClawConfigDir(), 'workspace');

interface SyncFailure {
  workspace: string;
  file: string;
  error: string;
}

interface SecuritySyncResult {
  targets: string[];
  succeeded: string[];
  skipped: string[];
  failures: SyncFailure[];
}

function expandHomePath(value: string): string {
  return value.startsWith('~') ? value.replace(/^~/, homedir()) : value;
}

async function canonicalizeOrPreservePath(rawPath: string): Promise<string> {
  const normalized = normalizeSecurityPath(expandHomePath(rawPath));
  if (!normalized) return '';

  try {
    return await realpath(normalized);
  } catch {
    return normalized;
  }
}

async function canonicalizeDeniedPaths(paths: string[]): Promise<string[]> {
  const out: string[] = [];
  for (const p of paths) {
    const resolved = await canonicalizeOrPreservePath(p);
    if (resolved) out.push(resolved);
  }
  return compactSecurityPaths(out);
}

function ensureObject(parent: Record<string, unknown>, key: string): Record<string, unknown> {
  const existing = parent[key];
  if (existing && typeof existing === 'object' && !Array.isArray(existing)) {
    return existing as Record<string, unknown>;
  }
  const created: Record<string, unknown> = {};
  parent[key] = created;
  return created;
}

async function readOpenclawConfig(): Promise<Record<string, unknown>> {
  try {
    return await readOpenClawConfigRecordRaw();
  } catch {
    return {};
  }
}

async function writeOpenclawConfig(config: Record<string, unknown>): Promise<void> {
  await updateOpenClawConfigRecord((current) => {
    Object.keys(current).forEach((key) => {
      delete current[key];
    });
    Object.assign(current, config);
  });
}

async function collectSecurityWorkspaces(config: Record<string, unknown>): Promise<string[]> {
  const agents = ensureObject(config, 'agents');
  const defaults = ensureObject(agents, 'defaults');
  const workspaces = new Set<string>();

  const addWorkspace = async (value: unknown): Promise<void> => {
    if (typeof value !== 'string') return;
    const normalized = await canonicalizeOrPreservePath(value);
    if (!normalized) return;
    workspaces.add(normalized);
  };

  await addWorkspace(DEFAULT_WORKSPACE_POLICY_ROOT);
  await addWorkspace(defaults.workspace);

  const list = Array.isArray(agents.list) ? agents.list : [];
  for (const item of list) {
    if (!item || typeof item !== 'object') continue;
    const entry = item as Record<string, unknown>;
    await addWorkspace(entry.workspace);
  }

  if (workspaces.size === 0) {
    workspaces.add(DEFAULT_WORKSPACE_POLICY_ROOT);
  }

  return [...workspaces].sort((a, b) => a.localeCompare(b));
}

function renderPolicyLine(label: string, enabled: boolean): string {
  return `- ${label}: ${enabled ? 'enabled' : 'disabled'}`;
}

function renderSecurityPolicyMarkdown(policy: SecurityPolicy, reminders: ReminderItem[]): string {
  const deniedLines = policy.prompt.deniedPaths.map((p) => `- ${p}`).join('\n');
  const selectedRules = policy.prompt.rules
    .map((key) => SECURITY_RULE_DEFINITIONS.find((rule) => rule.key === key))
    .filter((item): item is (typeof SECURITY_RULE_DEFINITIONS)[number] => Boolean(item));
  const ruleLines = selectedRules.map((rule) => `- ${rule.title}: ${rule.description}`).join('\n');
  const enabledReminders = reminders.filter((item) => item.enabled);
  const reminderLines = enabledReminders.map((item) => `- ${item.text}`).join('\n');
  return [
    '# SECURITY_POLICY.md',
    '',
    'This file is generated by ClawClaw to document current security policy.',
    '',
    'How enforcement works:',
    '- Denied directories are guidance written into workspace instructions so the agent avoids those paths.',
    '- Behavior restrictions are hard runtime blocks written into the OpenClaw tool deny list.',
    '',
    '## Persistent reminders',
    renderPolicyLine('status', enabledReminders.length > 0),
    enabledReminders.length > 0 ? reminderLines : '- not configured',
    '',
    '## Prompt directory denylist',
    renderPolicyLine('status', policy.prompt.enabled),
    policy.prompt.enabled ? deniedLines || '- (none configured)' : '- not configured',
    '',
    '## Preset restrictions',
    renderPolicyLine('status', policy.prompt.enabled && selectedRules.length > 0),
    selectedRules.length > 0 ? ruleLines : '- not configured',
    '',
  ].join('\n');
}

function mergeAgentsSecuritySection(
  existing: string,
  policy: SecurityPolicy,
  reminders: ReminderItem[],
): string {
  const enabledReminders = reminders.filter((item) => item.enabled);
  const selectedRules = policy.prompt.rules
    .map((key) => SECURITY_RULE_DEFINITIONS.find((rule) => rule.key === key))
    .filter((item): item is (typeof SECURITY_RULE_DEFINITIONS)[number] => Boolean(item));
  const reminderLines = enabledReminders.length > 0
    ? enabledReminders.map((item) => `- ${item.text}`).join('\n')
    : '- No persistent reminders are enabled right now.';
  const deniedPathLines = policy.prompt.enabled && policy.prompt.deniedPaths.length > 0
    ? policy.prompt.deniedPaths.map((p) => `- Never read from, write to, or browse inside \`${p}\`.`).join('\n')
    : '- No denied directories are configured right now.';
  const ruleLines = selectedRules.length > 0
    ? selectedRules.map((rule) => `- ${rule.title}: ${rule.description}`).join('\n')
    : '- No runtime hard blocks are configured right now.';
  const hasManagedContent =
    enabledReminders.length > 0
    || (policy.prompt.enabled && policy.prompt.deniedPaths.length > 0)
    || selectedRules.length > 0;

  const begin = existing.indexOf(POLICY_BEGIN);
  const end = existing.indexOf(POLICY_END);
  if (!hasManagedContent) {
    if (begin !== -1 && end !== -1) {
      const before = existing.slice(0, begin).trimEnd();
      const after = existing.slice(end + POLICY_END.length).trimStart();
      return [before, after].filter(Boolean).join('\n\n').trimEnd() + '\n';
    }
    return existing;
  }

  const section = [
    POLICY_BEGIN,
    '## Session Startup',
    'Treat the following managed rules as standing orders for every turn, including resumed and long-running conversations.',
    'If context is compacted, keep these rules active unless the user explicitly changes them in the current conversation.',
    '',
    '### Persistent Reminders',
    reminderLines,
    '',
    '## Red Lines',
    'These restrictions are managed by ClawClaw. Do not override them on your own.',
    '',
    '### Denied Directories',
    deniedPathLines,
    '',
    '### Runtime Hard Blocks',
    ruleLines,
    POLICY_END,
  ].join('\n');

  if (begin !== -1 && end !== -1) {
    return `${existing.slice(0, begin)}${section}${existing.slice(end + POLICY_END.length)}`;
  }
  return `${existing.trimEnd()}\n\n${section}\n`;
}

async function syncSecurityPolicyArtifacts(
  config: Record<string, unknown>,
  policy: SecurityPolicy,
  reminders: ReminderItem[],
): Promise<SecuritySyncResult> {
  const workspaces = await collectSecurityWorkspaces(config);
  const result: SecuritySyncResult = {
    targets: [...workspaces],
    succeeded: [],
    skipped: [],
    failures: [],
  };

  for (const workspace of workspaces) {
    const targetWorkspace = normalizeSecurityPath(expandHomePath(workspace));
    if (!targetWorkspace) {
      result.failures.push({ workspace, file: SECURITY_POLICY_FILE, error: 'Invalid workspace path' });
      continue;
    }

    const agentsPath = join(targetWorkspace, AGENTS_FILE);
    const policyPath = join(targetWorkspace, SECURITY_POLICY_FILE);

    try {
      await mkdir(targetWorkspace, { recursive: true });
      await writeFile(policyPath, renderSecurityPolicyMarkdown(policy, reminders), 'utf8');

      let existingAgents = '# AGENTS.md\n';
      try {
        existingAgents = await readFile(agentsPath, 'utf8');
      } catch {
        existingAgents = '# AGENTS.md\n';
      }

      const mergedAgents = mergeAgentsSecuritySection(existingAgents, policy, reminders);
      if (mergedAgents === existingAgents) {
        result.skipped.push(agentsPath);
      } else {
        await writeFile(agentsPath, mergedAgents, 'utf8');
      }

      result.succeeded.push(targetWorkspace);
    } catch (error) {
      result.failures.push({
        workspace: targetWorkspace,
        file: AGENTS_FILE,
        error: String(error),
      });
      logger.warn(`[security] Failed to sync policy docs for workspace: ${targetWorkspace}`, error);
    }
  }

  return result;
}

function buildPolicySnapshot(
  policy: SecurityPolicy,
  config: Record<string, unknown>,
): SecurityPolicySnapshot {
  const tools =
    config.tools && typeof config.tools === 'object' && !Array.isArray(config.tools)
      ? config.tools as Record<string, unknown>
      : {};
  const toolDeny = normalizeToolEntries(tools.deny);
  return createSecurityPolicySnapshot(policy, toolDeny);
}

async function normalizePolicyInput(body: Partial<SecurityPolicy>): Promise<SecurityPolicy> {
  const deniedPaths = await canonicalizeDeniedPaths(body.prompt?.deniedPaths || []);
  const rules = normalizeSecurityRules(body.prompt?.rules);

  return {
    prompt: {
      enabled: !!body.prompt?.enabled,
      deniedPaths,
      rules,
    },
  };
}

function normalizeToolEntries(values: unknown): string[] {
  if (!Array.isArray(values)) return [];
  return normalizeToolPolicyEntries(values.filter((item): item is string => typeof item === 'string'));
}

async function applyPolicyRuntimeConfig(
  config: Record<string, unknown>,
  previousPolicy: SecurityPolicy,
  nextPolicy: SecurityPolicy,
): Promise<{ managedToolDeny: string[]; totalToolDeny: string[] }> {
  // Rules are only enforced when the policy is enabled.
  // If disabled, we remove any previously applied managed denies but keep extra denies intact.
  const nextManaged = nextPolicy.prompt.enabled
    ? getManagedToolDenyForRules(nextPolicy.prompt.rules)
    : [];

  const tools = ensureObject(config, 'tools');
  const mergedDeny = mergeManagedToolDeny(
    normalizeToolEntries(tools.deny),
    previousPolicy.prompt.enabled ? previousPolicy.prompt.rules : [],
    nextPolicy.prompt.enabled ? nextPolicy.prompt.rules : [],
  );

  if (mergedDeny.length > 0) {
    tools.deny = mergedDeny;
  } else {
    delete tools.deny;
  }

  if (Object.keys(tools).length === 0) {
    delete config.tools;
  }

  await writeOpenclawConfig(config);

  return {
    managedToolDeny: nextManaged,
    totalToolDeny: mergedDeny,
  };
}

export async function handleSecurityRoutes(
  req: IncomingMessage,
  res: ServerResponse,
  url: URL,
  ctx: HostApiContext,
): Promise<boolean> {
  if (url.pathname === '/api/security/policy' && req.method === 'GET') {
    const current = normalizeSecurityPolicy(await getSetting('securityPolicy'));
    const config = await readOpenclawConfig();
    const appliedAt = await getSetting('securityPolicyAppliedAt');
    sendJson(res, 200, { ...buildPolicySnapshot(current, config), appliedAt });
    return true;
  }

  if (url.pathname === '/api/security/policy' && req.method === 'PUT') {
    try {
      const body = await parseJsonBody<Partial<SecurityPolicy>>(req);
      const policy = await normalizePolicyInput(body);

      // Reject saving an enabled policy with no content — this guards against
      // PUT being used without the apply check.
      if (policy.prompt.enabled && policy.prompt.deniedPaths.length === 0 && policy.prompt.rules.length === 0) {
        sendJson(res, 400, { success: false, error: 'Prompt policy enabled but no denied directories or preset restrictions configured.' });
        return true;
      }

      await setSetting('securityPolicy', policy);
      sendJson(res, 200, { success: true, policy });
    } catch (error) {
      sendJson(res, 500, { success: false, error: String(error) });
    }
    return true;
  }

  if (url.pathname === '/api/security/apply' && req.method === 'POST') {
    try {
      const payload = await parseJsonBody<Partial<SecurityPolicy>>(req);
      const policy = await normalizePolicyInput(payload);

      if (policy.prompt.enabled && policy.prompt.deniedPaths.length === 0 && policy.prompt.rules.length === 0) {
        sendJson(res, 400, { success: false, error: 'Prompt policy enabled but no denied directories or preset restrictions configured.' });
        return true;
      }

      const current = normalizeSecurityPolicy(await getSetting('securityPolicy'));
      const config = await readOpenclawConfig();
      const verify = await applyPolicyRuntimeConfig(config, current, policy);
      await setSetting('securityPolicy', policy);
      await setSetting('securityPolicyAppliedAt', Date.now());
      const reminders = normalizeReminders(await getSetting('reminders'));
      const syncResult = await syncSecurityPolicyArtifacts(config, policy, reminders);
      const gatewayRestartResult = ctx.gatewayApplyCoordinator.enqueue({
        source: 'security.apply',
        reason: 'security.apply',
        requires: 'restart_immediate',
        skipIfStopped: true,
      });

      const appliedAt = Date.now();
      sendJson(res, 200, {
        success: true,
        snapshot: buildPolicySnapshot(policy, config),
        verify,
        sync: syncResult,
        appliedAt,
        gatewayRestarted: gatewayRestartResult.accepted,
      });
    } catch (error) {
      sendJson(res, 500, { success: false, error: String(error) });
    }
    return true;
  }

  if (url.pathname === '/api/security/reset' && req.method === 'POST') {
    try {
      const config = await readOpenclawConfig();
      const current = normalizeSecurityPolicy(await getSetting('securityPolicy'));
      const verify = await applyPolicyRuntimeConfig(config, current, DEFAULT_SECURITY_POLICY);
      await setSetting('securityPolicy', DEFAULT_SECURITY_POLICY);
      await setSetting('securityPolicyAppliedAt', Date.now());
      const reminders = normalizeReminders(await getSetting('reminders'));
      const syncResult = await syncSecurityPolicyArtifacts(config, DEFAULT_SECURITY_POLICY, reminders);
      const gatewayRestartResult = ctx.gatewayApplyCoordinator.enqueue({
        source: 'security.reset',
        reason: 'security.reset',
        requires: 'restart_immediate',
        skipIfStopped: true,
      });

      const appliedAt = Date.now();
      sendJson(res, 200, {
        success: true,
        snapshot: buildPolicySnapshot(DEFAULT_SECURITY_POLICY, config),
        verify,
        sync: syncResult,
        appliedAt,
        gatewayRestarted: gatewayRestartResult.accepted,
      });
    } catch (error) {
      sendJson(res, 500, { success: false, error: String(error) });
    }
    return true;
  }

  if (url.pathname === '/api/security/reminders/sync' && req.method === 'POST') {
    try {
      const config = await readOpenclawConfig();
      const policy = normalizeSecurityPolicy(await getSetting('securityPolicy'));
      const reminders = normalizeReminders(await getSetting('reminders'));
      const syncResult = await syncSecurityPolicyArtifacts(config, policy, reminders);
      sendJson(res, 200, { success: true, sync: syncResult });
    } catch (error) {
      sendJson(res, 500, { success: false, error: String(error) });
    }
    return true;
  }

  if (url.pathname === '/api/security/reminders' && req.method === 'PUT') {
    try {
      const body = await parseJsonBody<{ reminders?: ReminderItem[] | string[] }>(req);
      const reminders = normalizeReminders(body.reminders ?? []);
      await setSetting('reminders', reminders);

      const config = await readOpenclawConfig();
      const policy = normalizeSecurityPolicy(await getSetting('securityPolicy'));
      const syncResult = await syncSecurityPolicyArtifacts(config, policy, reminders);

      sendJson(res, 200, { success: true, reminders, sync: syncResult });
    } catch (error) {
      sendJson(res, 500, { success: false, error: String(error) });
    }
    return true;
  }

  return false;
}
